
# Enhanced Ores - Configuration File

EnhancedOres:

    economy-item:
        material: GOLD_NUGGET
        item-meta:
            display-name: <!italic><gold>Złota moneta
            lore:
                - <gray>[-] </gray><yellow>Waluta serwerowa </yellow>
                - <gray>[-] </gray><green>Użycie -> </green><dark_green>Opłacenie działki, Kupienie przedmiotów. </dark_green>

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   You can write name of any ore here.
    #   Warning! You can only use blocks which names ends on "_ORE"
    #
    #   Example: COAL_ORE | IRON_ORE | GOLD_ORE
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    ores:
        - GOLD

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   Minimum drop chance is "0" - 0%         // it will not change no matter what you do!
    #   Maximum drop chance is "100" - 100%     // it will not change no matter what you do!
    #
    #   You can use number types of Integer, Float and Double.
    #   If you will set "drop-chance" under 1, the logic behind it will multiply it by 100.
    #
    #   Example: 0.95 -> 95% | 1 -> 1% | 55 -> 55%
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    drop-chance: 25