
# Enhanced Ores - Configuration File

EnhancedOres:

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   Database connection arguments
    #
    #   Those options are fully customizable. If you are not using MariaDB, look on internet
    #   for other engines with these keywords -> "hibernate", "dialect","(your database engine)"
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    # Database connection

    database:
        dialect:        MySQL8Dialect
        address:        localhost
        port:           3306
        database:       enhanced_ores

        username:       root
        password:       ""

    hibernate:
        show_sql:       false
        format_sql:     true
        sql_comments:   true

    # Economy item

    economy-item:
        material: GOLD_NUGGET
        item-meta:
            display-name: <!italic><gold>Golden coin
            lore:
                - <gray>[-] </gray><yellow>Server currency</yellow>
                - <gray>[-] </gray><green>Użycie -> </green><dark_green>Paying for plots, buying items.</dark_green>

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   You can write name of any ore here.
    #   Warning! You can only use all blocks which names ends on "_ORE"
    #
    #   Example: COAL_ORE | IRON_ORE | GOLD_ORE | DEEPSLATE_GOLD
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    # Ores from which drops currency

    ores:
        - DEEPSLATE_GOLD
    #   - GOLD
    #   - IRON
    #   - ...

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   Minimum drop chance is "0" - 0%         // it will not change no matter what you do!
    #   Maximum drop chance is "100" - 100%     // it will not change no matter what you do!
    #
    #   You can use number types of Integer, Float and Double.
    #   If you will set "drop-chance" under 1, the logic behind it will multiply it by 100.
    #
    #   Example: 0.95 -> 95% | 1 -> 1% | 55 -> 55%
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    # Drop chance

    drop-chance: 25