
# Enhanced Ores - Configuration File

EnhancedOres:

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   Database connection arguments
    #   Warning! Do not change (driver_class) if you have no idea what you're doing!
    #
    #   Those options are fully customizable. If you are not using MariaDB, look on internet
    #   for other engines with these keywords -> "hibernate", "dialect","(your database engine)"
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    database:
        dialect:        MariaDBDialect  #org.hibernate.dialect.MariaDBDialect
        address:        localhost    #jdbc:msql://83.168.108.1:3306/
        port:           3306
        database:       enhanced_ores

        username:       root
        password:       ""

    # Economy item

    economy-item:
        material: GOLD_NUGGET
        item-meta:
            display-name: <!italic><gold>Złota moneta
            lore:
                - <gray>[-] </gray><yellow>Waluta serwerowa </yellow>
                - <gray>[-] </gray><green>Użycie -> </green><dark_green>Opłacenie działki, Kupienie przedmiotów. </dark_green>

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   You can write name of any ore here.
    #   Warning! You can only use blocks which names ends on "_ORE"
    #
    #   Example: COAL_ORE | IRON_ORE | GOLD_ORE
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    ores:
        - GOLD
    #   - IRON
    #   - ...

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   Minimum drop chance is "0" - 0%         // it will not change no matter what you do!
    #   Maximum drop chance is "100" - 100%     // it will not change no matter what you do!
    #
    #   You can use number types of Integer, Float and Double.
    #   If you will set "drop-chance" under 1, the logic behind it will multiply it by 100.
    #
    #   Example: 0.95 -> 95% | 1 -> 1% | 55 -> 55%
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    drop-chance: 25